name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test1
      id: test1
      uses: education/autograding-io-grader@v1
      with:
        test-name: Test1
        setup-command: make main
        command: "./main"
        input: '234556'
        expected-output: |-
          Input Data >> DATA   : 2 -> 3 -> 4 -> 5 -> 5 -> 6
          RESULT : 3 -> 4 -> 5 -> 6 -> 6 -> 0
          SELL   : Day2 Day3 Day4 Day6
        comparison-method: contains
        timeout: 10
        max-score: 15
    - name: Test2
      id: test2
      uses: education/autograding-io-grader@v1
      with:
        test-name: Test2
        setup-command: make main
        command: "./main"
        input: '1321435'
        expected-output: |-
          Input Data >> DATA   : 1 -> 3 -> 2 -> 1 -> 4 -> 3 -> 5
          RESULT : 3 -> 4 -> 4 -> 4 -> 5 -> 5 -> 0
          SELL   : Day2 Day5 Day7
        comparison-method: contains
        timeout: 10
        max-score: 15
    - name: Test3
      id: test3
      uses: education/autograding-io-grader@v1
      with:
        test-name: Test3
        setup-command: make main
        command: "./main"
        input: '132435'
        expected-output: |-
          Input Data >> DATA   : 1 -> 3 -> 2 -> 4 -> 3 -> 5
          RESULT : 3 -> 4 -> 4 -> 5 -> 5 -> 0
          SELL   : Day2 Day4 Day6
        comparison-method: contains
        timeout: 10
        max-score: 14
    - name: Test4
      id: test4
      uses: education/autograding-io-grader@v1
      with:
        test-name: Test4
        setup-command: make main
        command: "./main"
        input: '111119'
        expected-output: |-
          Input Data >> DATA   : 1 -> 1 -> 1 -> 1 -> 1 -> 9
          RESULT : 9 -> 9 -> 9 -> 9 -> 9 -> 0
          SELL   : Day6
        comparison-method: contains
        timeout: 10
        max-score: 14
    - name: Test5
      id: test5
      uses: education/autograding-io-grader@v1
      with:
        test-name: Test5
        setup-command: make main
        command: "./main"
        input: '76591'
        expected-output: |-
          Input Data >> DATA   : 7 -> 6 -> 5 -> 9 -> 1
          RESULT : 9 -> 9 -> 9 -> 0 -> 0
          SELL   : Day4
        comparison-method: contains
        timeout: 10
        max-score: 14
    - name: Test6
      id: test6
      uses: education/autograding-io-grader@v1
      with:
        test-name: Test6
        setup-command: make main
        command: "./main"
        input: '123456'
        expected-output: |-
          Input Data >> DATA   : 1 -> 2 -> 3 -> 4 -> 5 -> 6
          RESULT : 2 -> 3 -> 4 -> 5 -> 6 -> 0
          SELL   : Day2 Day3 Day4 Day5 Day6
        comparison-method: contains
        timeout: 10
        max-score: 14
    - name: Test7
      id: test7
      uses: education/autograding-io-grader@v1
      with:
        test-name: Test7
        setup-command: make main
        command: "./main"
        input: '111'
        expected-output: |-
          Input Data >> DATA   : 1 -> 1 -> 1
          RESULT : 0 -> 0 -> 0
          SELL   :
        comparison-method: contains
        timeout: 10
        max-score: 14
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST1_RESULTS: "${{steps.test1.outputs.result}}"
        TEST2_RESULTS: "${{steps.test2.outputs.result}}"
        TEST3_RESULTS: "${{steps.test3.outputs.result}}"
        TEST4_RESULTS: "${{steps.test4.outputs.result}}"
        TEST5_RESULTS: "${{steps.test5.outputs.result}}"
        TEST6_RESULTS: "${{steps.test6.outputs.result}}"
        TEST7_RESULTS: "${{steps.test7.outputs.result}}"
      with:
        runners: test1,test2,test3,test4,test5,test6,test7
